export const FETCH_SPACES_REQUEST = 'FETCH_SPACES_REQUEST'
export const FETCH_SPACES_SUCCESS = 'FETCH_SPACES_SUCCESS'
export const FETCH_SPACES_FAILURE = 'FETCH_SPACES_FAILURE'

export const FETCH_SPACE_BY_ID_REQUEST = 'FETCH_SPACE_BY_ID_REQUEST'
export const FETCH_SPACE_BY_ID_SUCCESS = 'FETCH_SPACE_BY_ID_SUCCESS'
export const FETCH_SPACE_BY_ID_FAILURE = 'FETCH_SPACE_BY_ID_FAILURE'

export const INSERT_SPACES_REQUEST = 'INSERT_SPACES_REQUEST'
export const INSERT_SPACES_SUCCESS = 'INSERT_SPACES_SUCCESS'
export const INSERT_SPACES_FAILURE = 'INSERT_SPACES_FAILURE'
