export const FETCH_SPACES_REQUEST = 'FETCH_SPACES_REQUEST'
export const FETCH_SPACES_SUCCESS = 'FETCH_SPACES_SUCCESS'
export const FETCH_SPACES_FAILURE = 'FETCH_SPACES_FAILURE'

export const INSERT_SPACES_REQUEST = 'INSERT_SPACES_REQUEST'
export const INSERT_SPACES_SUCCESS = 'INSERT_SPACES_SUCCESS'
export const INSERT_SPACES_FAILURE = 'INSERT_SPACES_FAILURE'
